config:
  threading:
    pool:
      minimum: 10
      maximum: 100
      keep_alive: 30000
    queue:
      size: 1000
      # Available options: "FIFO", "UNSPECIFIED"
      order: "FIFO"
    name: "ExtensiveAPI-Thread-%d"